# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-07-21 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RPJOGA', '0002_auto_20190721_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minion_stage',
            old_name='hp_base',
            new_name='base_hp',
        ),
    ]
