# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-19 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPJOGA', '0002_auto_20200918_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='max_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='bonus_hp',
            field=models.IntegerField(default=0),
        ),
    ]
