# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPJOGA', '0003_auto_20200919_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='char',
            name='crit_s',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='skill',
            name='dano_mod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='s_d_m_id',
            field=models.IntegerField(default=0),
        ),
    ]
