# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-17 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPJOGA', '0004_auto_20200915_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy_skill',
            name='reduc',
        ),
        migrations.RemoveField(
            model_name='minion_skill',
            name='reduc',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='reduc',
        ),
        migrations.AddField(
            model_name='char',
            name='reduc',
            field=models.IntegerField(default=0),
        ),
    ]
