# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPJOGA', '0004_auto_20200915_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='invent',
            name='limit_qtd',
            field=models.IntegerField(default=0),
        ),
    ]
