# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-26 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPJOGA', '0004_auto_20200926_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='dano_base',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
