# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2020-09-26 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RPJOGA', '0005_skill_dano_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='dcrit_mid',
            field=models.IntegerField(default=0),
        ),
    ]
